# Generated by Django 5.2.1 on 2025-05-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gis_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deforestation",
            name="name",
            field=models.CharField(
                default="Unknown",
                help_text="Location name e.g., Dandora",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="pollution",
            name="name",
            field=models.CharField(
                default="Unknown",
                help_text="Location name e.g., Dandora",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="urbansprawl",
            name="name",
            field=models.CharField(
                default="Unknown",
                help_text="Location name e.g., Dandora",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="deforestation",
            name="forest_cover_loss",
            field=models.FloatField(help_text="Amount lost (in hectares)"),
        ),
        migrations.AlterField(
            model_name="urbansprawl",
            name="year",
            field=models.FloatField(),
        ),
    ]
